FROM aips_3gciv

MAINTAINER Ben Hugo <bhugo@ska.ac.za>

#Handle mounts (specify AIPSMOUNT) using -e when running
RUN chmod 777 /usr/local/AIPS/DA00/DADEVS.LIST
RUN chmod 777 /usr/local/AIPS/DA00/NETSP
COPY aipsrunner.sh /aipsrunner.sh
RUN chmod a+rx /aipsrunner.sh
ENTRYPOINT /aipsrunner.sh
#CMD ["/bin/bash","-c","if [ ! -d ${AIPSMOUNT} ]; then\n   echo \"You must specify AIPSMOUNT environment variable to valid mounted volume to load / store aips volumes\"; exit 1\n fi\n"]
#CMD echo "Remember to mount a valid volume with uvfits files as '/usr/local/AIPS/FITS' if you want uvfits reading support"
#CMD echo "Creating an AIPS mount in ${AIPSMOUNT}/LOCALHOST_2 if it doesn't exist already"
#CMD echo "-  ${AIPSMOUNT}/LOCALHOST_2" >> /usr/local/AIPS/DA00/DADEVS.LIST
#CMD echo "${AIPSMOUNT}/LOCALHOST_2 365.0    0    0    0    0    0    0    0    0" >> /usr/local/AIPS/DA00/NETSP
#CMD ["/bin/bash","-c","printf 'if [ ! -d ${AIPSMOUNT}/LOCALHOST_2 ]; then\n   mkdir ${AIPSMOUNT}/LOCALHOST_2 && touch ${AIPSMOUNT}/LOCALHOST_2/SPACE\nfi\n'"]

#CMD . /usr/local/AIPS/LOGIN.SH && aips da=all tv=local

